`timescale 1ns / 1ps

module testbench;
    reg clk;
    reg [2:0] in1;
    reg [4:0] in2;
    wire [4:0] out;

    module2 uut (
        .clk(clk),
        .in1(in1),
        .in2(in2),
        .out(out)
    );

    initial begin
        $dumpfile("waveform.vcd");
        $dumpvars(0, uut);

        // Initialize
        clk = 0;
        @(posedge clk);

        // Autogenerated code